cursoYoutube/Controllers/AreaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using cursoYoutube.Models;

namespace cursoYoutube.Controllers
{
    public class AreaController : Controller
    {
        //
        // GET: /Area/

        public AreaModel modelo = new AreaModel();

        public ActionResult Index()
        {
            return View(modelo.ListaAreas());
        }

        public ActionResult Detalles(int id) {
            var area = modelo.BuscarArea(id);
            return View(area);
        }

        public ActionResult Crear() {
            return View();
        }

        [HttpPost]
        public ActionResult Crear(C_Area a) {

            try
            {
                if (modelo.InsertarArea(a).Equals("OK"))
                {
                    return RedirectToAction("Index");
                }
                else {
                    return RedirectToAction("Crear");
                }
            }
            catch (Exception)
            {
                return View();
            }
        }

        public ActionResult Editar(int id) {
            var area = modelo.BuscarArea(id);
            return View(area);
        }

        [HttpPost]
        public ActionResult Editar(int id, C_Area a) {

            try
            {
                C_Area area = new C_Area();
                area.id_area = id;
                area.descripcion = a.descripcion;

                if (modelo.ActualizarArea(area).Equals("OK"))
                {
                    return RedirectToAction("Index");
                }
                else {
                    return RedirectToAction("Editar");                
                }
            }
            catch (Exception)
            {
                return View();
            }
        }

        public ActionResult Eliminar(int id) {


            var area = modelo.BuscarArea(id);
            return View(area);
        }

        [HttpPost]
        public ActionResult Eliminar(int id, FormCollection coleccion) {
            try
            {
                if (modelo.EliminarArea(id).Equals("OK"))
                {
                    return RedirectToAction("Index");
                }
                else
                { 
                    return RedirectToAction("Eliminar");
                }
            }
            catch (Exception)
            {
                return View();
            }
        }



    }
}

cursoYoutube/Controllers/CVPA2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using cursoYoutube.Models;

namespace cursoYoutube.Controllers
{
    public class CVPA2Controller : Controller
    {
        //
        // GET: /CVPA2/
        
        private readonly List<VentasMes> ventasMes = new List<VentasMes>()
        {
            new VentasMes()
            { 
                id = 1, 
                mes = "Enero",                 
                valor=200000, 
                DetalleMes = new List<DetalleMes>(){
                   new DetalleMes(){ id = 1, producto = "Producto 1", valor = 50000},
                   new DetalleMes(){ id = 1, producto = "Producto 2", valor = 50000},
                   new DetalleMes(){ id = 1, producto = "Producto 3", valor = 50000},
                   new DetalleMes(){ id = 1, producto = "Producto 4", valor = 50000}
                }
            },
            new VentasMes()
            { 
                id = 2, 
                mes = "Febrero", 
                valor=200000, 
                DetalleMes = new List<DetalleMes>(){
                   new DetalleMes(){ id = 1, producto = "Producto 1", valor = 100000},
                   new DetalleMes(){ id = 1, producto = "Producto 2", valor = 100000}
                }
            },
        };

        public ActionResult Index()
        {
            return View(ventasMes);
        }

        public ActionResult ViewDetails(int id)
        {
            var detalle = ventasMes
                            .Where(c => c.id == id)
                            .Select(c => c.DetalleMes)
                            .FirstOrDefault();
            return PartialView("_Details", detalle);
        }
    }
}

cursoYoutube/Controllers/CVPAController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using cursoYoutube.Models;

namespace cursoYoutube.Controllers
{
    public class CVPAController : Controller
    {
        List<CVPA_Cliente> objCliente = new List<CVPA_Cliente>();
        List<CVPA_Producto> objProducto = new List<CVPA_Producto>();

        //
        // GET: /CVPA/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(FormContext form)
        {
            return View();
        }

        public ActionResult ObtenerCliente()
        {
            CVPA_Cliente c;
            c = new CVPA_Cliente();
            c.Nombre="Pepito";
            c.Apellido = "Gonzalez";
            c.MostrarNombre = c.Nombre + " " + c.Apellido;
            c.Edad = 30;
            c.Profesion = "Camarero";
            objCliente.Add(c);

            c = new CVPA_Cliente();
            c.Nombre = "Tomas";
            c.Apellido = "Filipe";
            c.MostrarNombre = c.Nombre + " " + c.Apellido;
            c.Edad = 21;
            c.Profesion = "Cartero";
            objCliente.Add(c);

            return View("DetalleCliente", objCliente);
        }

        public ActionResult ObtenerProducto()
        {
            CVPA_Producto p;
            p = new CVPA_Producto();
            p.Nombre = "Tornillo";
            p.Fecha = DateTime.Now;
            p.Precio = 55.99;
            p.IsDisponible = true;
            objProducto.Add(p);

            p = new CVPA_Producto();
            p.Nombre = "Llave inglesa";
            p.Fecha = DateTime.Now;
            p.Precio = 54.99;
            p.IsDisponible = true;
            objProducto.Add(p);

            p = new CVPA_Producto();
            p.Nombre = "Sandalias";
            p.Fecha = DateTime.Now;
            p.Precio = 520.45;
            p.IsDisponible = false;
            objProducto.Add(p);

            return View("DetalleProducto", objProducto);
        }

        public ActionResult Vacio()
        {
            return View("vacio");
        }

    }
}

cursoYoutube/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using cursoYoutube.Models;

namespace cursoYoutube.Controllers
{
    public class ClienteController : Controller
    {
        //
        // GET: /Cliente/
        bdCursoYoutubeEntities entidad = new bdCursoYoutubeEntities();


        public ActionResult Index()
        {
            var listaClientes = entidad.C_Clientes;
            return View(listaClientes.ToList());
        }

        public ActionResult ListaDirecciones()
        {
            var listaClDirecciones = entidad.C_Direcciones;
            return View(listaClDirecciones.ToList());
        }

        public ActionResult ListaClientePorCP(string cp)
        {
            var modelo = from c in entidad.C_Clientes 
                         join d in entidad.C_Direcciones on c.id_cliente equals d.id_cliente
                         where d.cp == cp
                         select c;
            return View(modelo.ToList());
        }

        public ActionResult ListaClienteDireccion()
        {
            var modelo = from p in entidad.C_Clientes
                         join c in entidad.C_Direcciones on p.id_cliente equals c.id_cliente

                         select new Cliente
                         {
                             codigo = p.id_cliente,
                             nombre = p.nombre,
                             apellidos = p.apellidos,
                             cod_direccion = c.id_direccion,
                             direccion = c.calle,
                             localidad = c.localidad,
                             provincia = c.provincia,
                             cp = c.cp
                         };
            return View(modelo.ToList());

        }


    }
}

cursoYoutube/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
    <head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Mi aplicación ASP.NET MVC</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryval")
        <script src="../../Scripts/underscore.js" type="text/javascript"></script>
        @Styles.Render("~/Content/bootstrapcss")
        @Scripts.Render("~/bundles/bootstrapjs")
        @RenderSection("styles",required:false)
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("su logotipo aquí", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul class="menu">
                            <li>@Html.ActionLink("Inicio", "Index", "Home")</li> | 
                            <li>@Html.ActionLink("Acerca de", "About", "Home")</li> | 
                            <li>@Html.ActionLink("Contacto", "Contact", "Home")</li> | 
                            <li>@Html.ActionLink("Clientes", "Index", "Cliente")</li> | 
                            <li>@Html.ActionLink("Direcciones", "ListaDirecciones", "Cliente")</li> | 
                            <li>@Html.ActionLink("Clientes y direcciones", "ListaClienteDireccion", "Cliente")</li> | 
                            <li>@Html.ActionLink("CRUB", "Index", "crubDirecciones")</li> | 
                            <li>@Html.ActionLink("Areas", "Index", "Area")</li>  |        
                        </ul>
                        <ul class="menu">
                            <li>@Html.ActionLink("Vista Parcial", "Index", "VistaParcial")</li> | 
                            <li>@Html.ActionLink("Tablas Maestro detalle Ajax", "Index", "MaestroDetalle")</li> | 
                            <li>@Html.ActionLink("Cargar vistas parciales con Ajax", "Index", "CVPA")</li> |
                            <li>@Html.ActionLink("Cargar vistas parcial con Ajax 2", "Index", "CVPA2")</li> |    
                        </ul>
                        <ul class="menu">
                            <li>@Html.ActionLink("WebGrid", "Index", "WebGrid")</li> |   
                            <li>@Html.ActionLink("WebGrid rendimiento optimizado", "Index2", "WebGrid")</li> |                               
                            <li>@Html.ActionLink("WebGrid con AJAX", "WebGridAjax", "WebGrid")</li> | 
                            <li>@Html.ActionLink("WebGrid con filtros", "Index", "WebGridFiltros")</li> | 
                        </ul>
                        <ul class="menu">
                            <li>@Html.ActionLink("ddl en cascada (Ajax)", "Index", "ddlCascada")</li> | 
                            <li>@Html.ActionLink("ddl en cascada con Entity y Ajax", "Index", "ddlCascadaSQlyajax")</li> |
                            <li>@Html.ActionLink("Ajax Editor Demo", "Index", "EditorDemo")</li> |    
                        </ul>
                       <strong>Multiples modelos en una vista</strong> - http://www.codeproject.com/Articles/687061/Multiple-Models-in-a-View-in-ASP-NET-MVC-MVC
                        <ul class="menu">
                            <li>@Html.ActionLink("ViewData Demo", "ViewDataDemo", "MultiplesModelos")</li> |
                            <li>@Html.ActionLink("ViewBag Demo", "ViewBagDemo", "MultiplesModelos")</li> |
                            <li>@Html.ActionLink("PartialView Demo", "PartialViewDemo", "MultiplesModelos")</li> |
                            <li>@Html.ActionLink("TempData Demo", "TempDataDemo", "MultiplesModelos")</li> |
                            <li>@Html.ActionLink("ViewModel Demo", "ViewModelDemo", "MultiplesModelos")</li> |
                            <li>@Html.ActionLink("Tuple Demo", "TupleDemo", "MultiplesModelos")</li> | 
                        </ul>
                        <strong>Curso MVP</strong> 
                        <ul class="menu">
                            <li>@Html.ActionLink("Intercambio de datos estructurados", "Index", "IntercambioDatosEstructurados")</li> |
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            <div style=" padding-left:50px">
                <p>Como incluir varias tablas en una "select" de entrity: 
                <br />
                var lq_paginas = db.LQ_Paginas.Include("LQ_Escenario").Include("LQ_MenuEscenario").Include("LQ_TipoPagina");</p>
            </div>
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET MVC</p>
                </div>
            </div>
        </footer>

        @RenderSection("scripts", required: false)
    </body>
</html>